### ISSUE TITLE
召唤石选择界面 UI位置不对

### ISSUE THREAD

**Issue by Keityo** [zy410419243/Liver-collection#1]
![image](https://user-images.githubusercontent.com/34365726/42153539-f86284de-7e15-11e8-8542-f81b3ca93f8d.png)
![image](https://user-images.githubusercontent.com/34365726/42153636-470439c0-7e16-11e8-8f57-21432d2b916f.png)

在选择友召界面时，如果选择比较上方的石头，选择队伍界面会正确出现在顶部，选择比较下面的石头时，选择队伍界面会如图所示出现在比较下方，主角LB界面也出现过同样情况，确认时候的UI会直接出现在底部

**Comment by zy410419243** [comment]
更新一下版本试试？
