### ISSUE TITLE
开了扩展过后，转世路径点击会错位或者点不起

### ISSUE THREAD

**Issue by strike94** [zy410419243/Liver-collection#2]
在打转世需要点击路径的时候，经常是错位点击才能点中，换成最新的过后就直接点击不上了。。

**Comment by zy410419243** [comment]
可以先看看[这里](http://bbs.ngacn.cc/read.php?tid=14415132&page=2#pid283966693Anchor)
转世可能只能先改成1.5了，这个我得查查怎么改

**Comment by saiwfy** [comment]
补充一个 除了转世错位之外 
主线地图 选择岛屿那个界面 也会错位不知道是不是同一个问题。

**Comment by zy410419243** [comment]
窗口缩放功能已移除
